### PR TITLE
HOTFIX for MASTER: MAT-501 & MAT-502 Update HelpDesk Email for automatically generated emails and NO REPLY emails

### PR DESCRIPTION
**Pull request by ghost**
MAT-501  Update HelpDesk Email for automatically generated NO REPLY emails
MAT-502 Update HelpDesk Email for automatically generated emails

### CODE REVIEW

**Comment by adongare** [comment]
I see it's a feature branch. is this not supposed to be hotfix?

**Comment by serhii-ilin** [comment]
@adongare - oh, well. you mean it should be in a hotfix branch folder? I forgot about that. Is it critical? The branch will be removed as soon as its merged

**Comment by adongare** [comment]
In my opinion this will cause lot of conflicts when we do release or merge develop into master because we already have these files changes in develop as well. let me know your thoughts

**Comment by serhii-ilin** [comment]
@adongare same commits have been already merged into a different feature branch as a foundation for its changes. See PR for develop branch. So, this will not cause any conflicts.

**Comment by serhii-ilin** [comment]
@adongare  - we do need to have separate PRs because HOTFIX is much simpler. It doesn't include refactoring.

**Comment by adongare** [comment]
@serhii-ilin If we don't have any conflicts with other change should be good.

**Review by adongare — APPROVED** [review]

**Review by nicole-hunter — APPROVED** [review]

**Pull request merged**
